### ISSUE TITLE
Внедрить слайдер в блоке Наши новости

### ISSUE THREAD

**Issue by konstantin-agafonov** [AlexeyShaykov/bf-kovcheg#1]
Внедрить слайдер в блоке Наши новости

**Comment by AlexeyShaykov** [comment]
@konstantin-agafonov нужны слайды.

**Comment by konstantin-agafonov** [comment]
Слайды - это элементы с классом col-news. В моменте на экране сделать два слайда. Щас пока размножить те два слайда, которые щас есть в вёрстке.
